EPISODES_COUNT = 5000
LEARNING_FACTOR = 0.2 # learning factor
DISCOUNT_FACTOR = 0.9 # discount factor
EPSILON_GREEDY_FACTOR_MINIMUM = 0
EPSILON_GREEDY_FACTOR_MAXIMUM = 0.8
RANDOM_Q_VALUE_MINIMUM = -1
RANDOM_Q_VALUE_MAXIMUM = 1
STATE_POSITION_BUCKETS = 120
STATE_VELOCITY_BUCKETS = 150
EVALUATION_EPISODES_COUNT = 50

ACTIONS = [
    0, # move left
    1, # stay
    2, # move right
]