// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLAppML.Model;

namespace MLAppML.BuilderApp
{
    class Program
    {
        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();
        }
    }
}
